# Notes:
#   - Minimal appveyor.yml file is an empty file. All sections are optional.
#   - Indent each level of configuration with 2 spaces. Do not use tabs!
#   - All section names are case-sensitive.
#   - Section names should be unique on each level.

#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: b{build}

# branches to build
branches:
  # whitelist
  only:
    - master
    
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{build}"
  assembly_file_version: "{build}"
  assembly_informational_version: "{build}"
  
before_build:
  - nuget restore

after_build:
  - ps: >-

        New-Item -Path .\Wrapper\RunTimes\$env:appveyor_build_version -ItemType directory

        Copy-Item -Path .\Launcher\bin\Debug\* -Destination .\Wrapper\

        Copy-Item -Path .\ProShipDesktop\bin\Debug\* -Destination .\Wrapper\RunTimes\$env:appveyor_build_version

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:

  # pushing a single file with environment variable in path and "Deployment name" specified
  - path: .\ProShipDesktop\bin
    name: Patch
    type: zip

  - path: .\Wrapper
    name: ProShip$(appveyor_build_version)
    type: zip

deploy:
  tag: $(APPVEYOR_REPO_TAG_NAME)
  release: ProShip-$(APPVEYOR_REPO_TAG_NAME)$(appveyor_build_version)
  description: '$(APPVEYOR_REPO_TAG_NAME)'
  provider: GitHub
  auth_token:
    secure: qBTwziKBi/xxO3hYtkgOboy4xk7TujdmY1vRv9gofrqSpLJlZk7hakTpwClViD/+ # your encrypted token from GitHub
  artifact: ProShipDesktop\ProShip.zip            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    APPVEYOR_REPO_TAG: true        # deploy on tag push only