using System;
using System.Collections.Generic;

namespace LibProShip.StaticResources
{
    public enum ShipType
    {
        Unknown = 0,
        Destroyer = 1,
        Cruiser = 2,
        Battleship = 3,
        AirCarrier = 4,
        Submarine = 5
    }

    public sealed class ShipDefinition
    {
        private ShipDefinition(long shipId, string shipName, ShipType shipType, int tier)
        {
            ShipId = shipId;
            ShipName = shipName;
            ShipType = shipType;
            Tier = tier;
        }

        public long ShipId { get; }
        public string ShipName { get; }
        public ShipType ShipType { get; }
        public int Tier { get; }

        public static readonly IEnumerable<ShipDefinition> ShipShipDefinitions = new[]
        {
            new ShipDefinition(3760109552L, "Alaska", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(3764271056L, "Gallant", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3764303056L, "Huanghe", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3762205904L, "Irian", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3340678608L, "[Moskva]", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3756963280L, "Varyag", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(3554555600L, "Shinonome", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3667801808L, "Asashio B", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3761190608L, "Musashi", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(3553540080L, "Flint", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3763255248L, "Belfast", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3522082512L, "ARP Nachi", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3532568272L, "Eastern Dragon", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3762239184L, "Kii", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3752736720L, "Cossack", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3763221968L, "Leningrad", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(3332323024L, "[Yamato]", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(3315513040L, "[Zao]", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3763287760L, "Ashitaka", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(3751753552L, "Jean Bart", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(3764270896L, "T-61", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3333404368L, "[Hakuryu]", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 10),
            new ShipDefinition(3338548944L, "[Shimakaze]", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(3551442640L, "ARP Haguro", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3762239440L, "Vanguard", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3554588464L, "HSF Admiral Graf Spee", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"),
                6),
            new ShipDefinition(3762173744L, "Z-39", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(3667867440L, "Tirpitz B", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3659445712L, "Admiral Makarov", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3552491216L, "ARP Takao", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3764303216L, "Perth", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3335501808L, "[Midway]", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 10),
            new ShipDefinition(3764336432L, "Prinz Eitel Friedrich",
                (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(3551409616L, "Neustrashimy", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(3761157584L, "Kronshtadt", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(3553539792L, "ARP Ashigara", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3761190896L, "Missouri", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(3762272048L, "Graf Zeppelin", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 8),
            new ShipDefinition(3555636944L, "ARP Myoko", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3762206160L, "Mikhail Kutuzov", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3764270832L, "Leone", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3764336336L, "Mutsu", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(3762239472L, "Alabama", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3762239216L, "Roma", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3760109008L, "Stalingrad", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3668883440L, "Boise", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3763255024L, "Duca degli Abruzzi", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"),
                7),
            new ShipDefinition(3763320528L, "Kaga", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 7),
            new ShipDefinition(3762173936L, "Kidd", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3763288048L, "W. Virginia 1941", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"),
                6),
            new ShipDefinition(3763254608L, "Nueve de Julio", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3555670000L, "Texas", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3764303312L, "Molotov", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3764303696L, "De Grasse", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3764303664L, "Admiral Graf Spee", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3550394352L, "Salem", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3763288016L, "Hood", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(3762206512L, "Prinz Eugen", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3340678960L, "[Hindenburg]", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3765351888L, "Krasny Krym", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(3742316496L, "Duke of York", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(3552523984L, "ARP Hiei", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3764336624L, "Arizona", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(3762206704L, "Wichita", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3445536592L, "Brennus", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3764270928L, "Aigle", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3749623248L, "STALINGRAD #2", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3340711728L, "[Großer Kurfürst]", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"),
                10),
            new ShipDefinition(3760109264L, "Azuma", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3553572560L, "ARP Haruna", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3760142160L, "Bourgogne", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(3763320816L, "Saipan", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 7),
            new ShipDefinition(3764336464L, "Dunkerque", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(3763221872L, "Haida", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(3543054032L, "Southern Dragon", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3554621136L, "ARP Kirishima", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3762272240L, "Enterprise", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 8),
            new ShipDefinition(3667834576L, "Atago B", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3751720400L, "Lazo", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3555669712L, "ARP Kongō", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3667867632L, "Massachusetts B", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"),
                8),
            new ShipDefinition(3762239312L, "Gascogne", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3764270288L, "Anshan", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3551410160L, "Black", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(3751687888L, "Asashio", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3333371888L, "[Montana]", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(3762173136L, "Loyang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3340711888L, "[Conqueror]", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(3764303600L, "Duca d'Aosta", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3764271088L, "Monaghan", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(3762173776L, "Le Terrible", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3552524272L, "Alabama ST", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3751753712L, "Massachusetts", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(3752802256L, "Nelson", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(3763255280L, "Indianapolis", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3763287856L, "Scharnhorst", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(3337500656L, "[Gearing]", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(3765319120L, "Okhotnik", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(3340645840L, "[Grozovoi]", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(3552458448L, "HSF Harekaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3765352144L, "Yahagi", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4078876656L, "Dallas", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(4182652112L, "Gadjah Mada", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(3767449040L, "Oleg", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4183733712L, "Budyonny", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(4079891920L, "Podvoisky", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4075697872L, "Yūgumo", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4181604048L, "Akizuki", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4180554960L, "Chung Mu", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4183701456L, "Icarus", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4184815408L, "König", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3765384656L, "Oktyabrskaya Revolutsiya",
                (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(3767449296L, "Katori", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4074649296L, "Harugumo", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4181637104L, "Baltimore", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4184750032L, "Acasta", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4180588496L, "Neptune", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(3766433584L, "Viribus Unitis", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4182652368L, "Udaloi", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4182685680L, "New Orleans", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4179539920L, "Minotaur", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3767416784L, "Campbeltown", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4181637072L, "Edinburgh", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4179506992L, "Z-52", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4180555568L, "Z-46", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(3767482160L, "König Albert", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4184749776L, "Mutsuki", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4076746448L, "Kagero", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3767482320L, "Dreadnought", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4182685648L, "Fiji", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4184782640L, "Königsberg", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4077828080L, "Helena", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4179539408L, "Moskva", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(4077795024L, "Shiratsuyu", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4183734224L, "Leander", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(4181669680L, "Bismarck", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(4182652720L, "Leberecht Maass", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4180587984L, "Dmitri Donskoi", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(4078843600L, "Hatsuharu", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4065212112L, "Kitakaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4179539792L, "Henri IV", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(4184782800L, "Emerald", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4179572688L, "Conqueror", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(4183701296L, "Ernst Gaede", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4179506384L, "Yueyang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4181636560L, "Chapayev", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4183766992L, "Queen Elizabeth", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"),
                6),
            new ShipDefinition(4184749872L, "T-22", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4179539760L, "Hindenburg", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(3765384944L, "Giulio Cesare", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(4182685136L, "Shchors", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(3768465392L, "Smith", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4181669840L, "Monarch", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(4183766864L, "Normandie", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(4182652624L, "Akatsuki", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4181669712L, "Richelieu", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(4181604144L, "Z-23", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4182685520L, "Algérie", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4074682352L, "Worcester", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(4182718416L, "King George V", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(4181636912L, "Admiral Hipper", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(3971888592L, "Kiev", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4184782288L, "Kirov", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4183701200L, "Fubuki", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4182685488L, "Yorck", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4183734096L, "La Galissonnière", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3769513264L, "Błyskawica", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4181636944L, "Charles Martel", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4075730928L, "Seattle", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(4180588336L, "Roon", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(4184782672L, "Émile Bertin", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4179506640L, "Khabarovsk", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4183734064L, "Nürnberg", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(4179572560L, "République", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(4181603536L, "Hsienyang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(3767416176L, "Vampire", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4074649040L, "Grozovoi", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4180621136L, "Alsace", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(4179507152L, "Daring", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4179572528L, "Großer Kurfürst", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"),
                10),
            new ShipDefinition(4180588528L, "Buffalo", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(4180555728L, "Jutland", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4180621104L, "Friedrich der Große",
                (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(4076746192L, "Ognevoi", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4076779504L, "Cleveland", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4182718288L, "Lyon", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(4181604304L, "Lightning", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4183700688L, "Fushun", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4184749264L, "Jianwei", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4180621264L, "Lion", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(4183766832L, "Bayern", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(4077794768L, "Minsk", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4180588368L, "Saint-Louis", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(3767449584L, "Charleston", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4182652880L, "Jervis", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(3768497968L, "Emden", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4182718256L, "Gneisenau", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(4183734256L, "Pensacola", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(3865982416L, "Tashkent", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4078843344L, "Gnevny", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4285445840L, "Mogami", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4186846416L, "Phra Ruang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4185830864L, "Svietlana", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4186879440L, "Bogatyr", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4277024464L, "Fūjin", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4279219920L, "Taiho", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 9),
            new ShipDefinition(4286461936L, "Benson", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 8),
            new ShipDefinition(4281284304L, "Amagi", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(4259264496L, "New Mexico", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(4185798608L, "Wakeful", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4290688720L, "Yūbari", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4287542992L, "Aoba", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 6),
            new ShipDefinition(4248745968L, "Marblehead", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4187895760L, "Medea", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4288657392L, "Independence", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 6),
            new ShipDefinition(4268635856L, "Kamikaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4282365648L, "Shokaku", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 8),
            new ShipDefinition(4272895696L, "Izumo", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(4287575760L, "Kongo", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(4255037136L, "Atago", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 8),
            new ShipDefinition(4283381456L, "Mikasa", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 2),
            new ShipDefinition(4187928528L, "Weymouth", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4186847184L, "Valkyrie", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4187895600L, "V-25", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4283414224L, "Hiryu", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 7),
            new ShipDefinition(4289640144L, "Furutaka", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4186912720L, "Bellerophon", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4290754544L, "Langley", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 4),
            new ShipDefinition(4185831216L, "Karlsruhe", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4286494416L, "Myoko", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4185863984L, "Kaiser", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4280170192L, "Tachibana Lima", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4258182864L, "Chikuma", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4286527184L, "Ishizuchi", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4281284592L, "Arkansas Beta", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4256085712L, "Hashidate", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4186846672L, "Derzki", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4259231440L, "Zao", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(4284430032L, "Nagato", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(4282333168L, "North Carolina", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 8),
            new ShipDefinition(4282300112L, "Ibuki", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 9),
            new ShipDefinition(4185831376L, "Danae", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4282267344L, "Shimakaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4187895248L, "Storozhevoi", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4288624336L, "Fuso", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(4288591856L, "Atlanta", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 7),
            new ShipDefinition(4274927600L, "Clemson", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4185798448L, "V-170", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4284397008L, "Diana Lima", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4186912592L, "Turenne", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4186912560L, "Nassau", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4247697392L, "Marblehead Lima", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4186879792L, "Kolberg", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4288624624L, "New York", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(4277122768L, "Hakuryu", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 10),
            new ShipDefinition(4267587280L, "Kamikaze R", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4279154384L, "Tenryu", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4273911792L, "Des Moines", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 10),
            new ShipDefinition(4285511376L, "Ryujo", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 6),
            new ShipDefinition(4277090288L, "Montana", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(4188977104L, "Black Swan", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4186879824L, "Friant", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4185831248L, "Duguay-Trouin", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4186847024L, "G-101", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4280170480L, "Nicholas", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4286527472L, "Colorado", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 7),
            new ShipDefinition(4281317360L, "Essex", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 9),
            new ShipDefinition(4279220208L, "Midway", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 10),
            new ShipDefinition(4184815568L, "Iron Duke", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(4185864016L, "Courbet", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4264441840L, "Sims", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4281251536L, "Kuma", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4276041712L, "Iowa", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 9),
            new ShipDefinition(4269684432L, "Wakatake", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4281219056L, "Gearing", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 10),
            new ShipDefinition(4276041424L, "Yamato", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 10),
            new ShipDefinition(4185864144L, "Orion", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4187928016L, "Novik", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4289640432L, "Omaha", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4272830448L, "Fletcher", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 9),
            new ShipDefinition(4288657104L, "Zuiho", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 5),
            new ShipDefinition(4269717488L, "Phoenix", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4188976592L, "Orlan", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4266538992L, "Wickes", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 3),
            new ShipDefinition(4284463088L, "Ranger", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 7),
            new ShipDefinition(4187928400L, "Jurien de la Gravière", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"),
                2),
            new ShipDefinition(4290689008L, "St. Louis", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4187894992L, "Longjiang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4186879952L, "Caledon", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4288559088L, "Mahan", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 7),
            new ShipDefinition(4267620048L, "Iwaki Alpha", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 4),
            new ShipDefinition(4184815440L, "Bretagne", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 5),
            new ShipDefinition(4290721776L, "Wyoming", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4188976976L, "Bougainville", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4289607664L, "Farragut", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 6),
            new ShipDefinition(4188976336L, "Chengan", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4185797840L, "Shenyang", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4282365936L, "Lexington", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 8),
            new ShipDefinition(4185798096L, "Izyaslav", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4290655952L, "Minekaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4292851408L, "Hosho", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 4),
            new ShipDefinition(4291737584L, "Albany", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4292851696L, "Bogue", (ShipType) Enum.Parse(typeof(ShipType), "AirCarrier"), 5),
            new ShipDefinition(4292818896L, "Warspite", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 6),
            new ShipDefinition(4292786160L, "Chester", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4292753392L, "Sampson", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4293867216L, "Kawachi", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4293834544L, "Hermelin", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4291770064L, "Myogi", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4292785968L, "Dresden", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4293867504L, "South Carolina", (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 3),
            new ShipDefinition(4291737040L, "Murmansk", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 5),
            new ShipDefinition(4293801424L, "Gremyashchy", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 5),
            new ShipDefinition(4293834736L, "Erie", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 1),
            new ShipDefinition(4293834192L, "Aurora", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 3),
            new ShipDefinition(4292785616L, "Diana", (ShipType) Enum.Parse(typeof(ShipType), "Cruiser"), 2),
            new ShipDefinition(4293866960L, "Imperator Nikolai I",
                (ShipType) Enum.Parse(typeof(ShipType), "Battleship"), 4),
            new ShipDefinition(4291704528L, "Isokaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 4),
            new ShipDefinition(4293801680L, "Tachibana", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4292753104L, "Umikaze", (ShipType) Enum.Parse(typeof(ShipType), "Destroyer"), 2),
            new ShipDefinition(4292818736L, "Tirpitz", ShipType.Battleship, 8),
        };
    }
}